Set-WindowsExplorerOptions -EnableShowHiddenFilesFoldersDrives -EnableShowProtectedOSFiles -EnableShowFileExtensions

cinst 7zip
cinst notepadplusplus
cinst DotNet4.5
cinst powershell4
cinst newrelicserver
